# Generated by Django 5.2.13 on 2026-05-17 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveIntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.doctor')),
            ],
            options={
                'ordering': ['doctor', 'weekday', 'start_time'],
                'unique_together': {('doctor', 'weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('CHECKUP', 'Check-up'), ('OPERATING', 'Operating Theater'), ('WARD', 'Ward'), ('EXAM', 'Examination'), ('ICU', 'Intensive Care Unit')], max_length=10)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('CLEANING', 'Cleaning')], default='AVAILABLE', max_length=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='accounts.department')),
            ],
            options={
                'ordering': ['department', 'floor', 'number'],
                'unique_together': {('department', 'number')},
            },
        ),
    ]
